export const FETCH_STAGE_REQUEST = 'stage/FETCH_STAGE_REQUEST';
export const FETCH_STAGE_SUCCESS = 'stage/FETCH_STAGE_SUCCESS';
export const FETCH_STAGE_ERROR = 'stage/FETCH_STAGE_ERROR';
export const HYDRATE_STAGE = 'stage/HYDRATE_STAGE';